version: '3.8'

networks: 
  court-finder:
  
services:

  court-finder-api-webserver:
    build: 
      context: ./infrastructure/docker/nginx
      dockerfile: Dockerfile
    container_name: court-finder-api-webserver
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./infrastructure/web/nginx/conf/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - court-finder-api-app
      - court-finder-api-db
    networks:
      - court-finder

  court-finder-api-app: 
    build:
      context: infrastructure/docker/php
      dockerfile: Dockerfile
    container_name: court-finder-api-app
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/html
    networks: 
      - court-finder

  court-finder-api-db:
    image: mysql:8.0.22
    container_name: court-finder-api-db
    ports:
      - "3306:3306"
    volumes:
      - ./infrastructure/db/mysql/data:/var/lib/mysql
      - ./infrastructure/db/mysql/sql:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always 
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - court-finder